name: Deploy to Zama Testnet

on:
  workflow_dispatch:  # Manual trigger from GitHub UI
  push:
    branches:
      - main
    paths:
      - 'scripts/deploy-and-configure.js'
      - 'contracts/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Deploy to Zama Testnet
        run: npx hardhat run scripts/deploy-and-configure.js --network zama_fhevm
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      
      - name: Commit deployment results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .env.production deployments/
          git commit -m "🚀 Auto-deploy: Zama Testnet deployment" || echo "No changes to commit"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
